train:
  # dataset_base_path: '/raid/persistent_scratch/saaf/vt1/dataset'
  dataset_base_path: './dataset'
  train_test_split: .8
  image_size: 128
  train_batch_size: 8
  test_batch_size: 8
  learning_rate: 1e-4
  lr_warmup_steps: 500
  num_epochs: 10
  seed: 42
  output_dir: '24-12-05_ddpm-swissaerial_forest_eval_10_1000'
  subset_size: 1000
  mixed_precision: 'no'
  gradient_accumulation_steps: 1
  save_image_epochs: 1
  save_model_epochs: 5