train:
  output_dir: '/raid/persistent_scratch/saaf/vt1/runs/24-12-28_mae-swissaerial_conditional_as17'
  # dataset_base_path: '/raid/persistent_scratch/saaf/vt1/dataset'
  dataset_base_path: ../02_model/dataset
  subset_size: 5
  train_test_split: .5
  image_size: 224
  patch_size: 16
  num_channels: 4
  hidden_size: 768
  num_hidden_layers: 12
  num_attention_heads: 12
  intermediate_size: 3072
  mask_ratio: 0.75
  train_batch_size: 16
  test_batch_size: 16
  mixed_precision: 'no'
  learning_rate: 1.5e-4
  num_epochs: 1_000
  gradient_accumulation_steps: 1
  save_image_epochs: 100
  save_model_epochs: 5000
eval:
  checkpoint: trained/24-12-30_mae-siwwaerial_conditional_as17/checkpoint_354/
  output_dir: eval/24-12-30_mae-siwwaerial_conditional_as17/
  dataset_base_path: eval/dataset
  eval_batch_size: 8
fine_tune:
  checkpoint: trained/24-12-30_mae-swissaerial_conditional_as17/checkpoint_354/
  output_dir: fine_tune/24-12-30_mae-swissaerial_conditional_as17_9/
  num_epochs: 10_000
  mask_ratio: 0.75